price:
  enable: true
  min: 1000.0
  max: 100000.0

gameconfig:
  spdrawchance: 20.0
  coin: 10
  bet: 2
  round: 3
  clocktime: 30



cardconfig:
  spcardmaterial: PAPER
  cardmaterial: PAPER
  invisiblecsm: 0

  cardcsm:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11

  spcards:
    1:
      enable: true
      csm: 0
    2:
      enable: true
      csm: 0
    3:
      enable: true
      csm: 0
    4:
      enable: true
      csm: 0
    5:
      enable: true
      csm: 0
    6:
      enable: true
      csm: 0
    7:
      enable: true
      csm: 0
    8:
      enable: true
      csm: 0
    9:
      enable: true
      csm: 0
    10:
      enable: true
      csm: 0
    11:
      enable: true
      csm: 0
    12:
      enable: true
      csm: 0
    13:
      enable: true
      csm: 0
    14:
      enable: true
      csm: 0
    15:
      enable: true
      csm: 0
    16:
      enable: true
      csm: 0
    17:
      enable: true
      csm: 0