price:
  enable: true
  min: 1000.0
  max: 100000.0

gameconfig:
  spdrawchance: 20.0
  coin: 10
  bet: 2
  round: 3
  clocktime: 30



cardconfig:
  spcardmaterial: SPRUCE_SAPLING
  cardmaterial: SPRUCE_SAPLING
  invisiblecsm: 12

  cardcsm:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11

  draw:
    - 20
    - 21
    - 22
    - 23
    - 24

  spcards:
    1:
      enable: true
      csm: 0
    2:
      enable: true
      csm: 33
    3:
      enable: true
      csm: 34
    4:
      enable: true
      csm: 25
    5:
      enable: true
      csm: 31
    6:
      enable: true
      csm: 32
    7:
      enable: true
      csm: 39
    8:
      enable: true
      csm: 13
    9:
      enable: true
      csm: 14
    10:
      enable: true
      csm: 15
    11:
      enable: true
      csm: 35
    12:
      enable: true
      csm: 36
    13:
      enable: true
      csm: 37
    14:
      enable: true
      csm: 38
    15:
      enable: true
      csm: 26
    16:
      enable: true
      csm: 27
    17:
      enable: true
      csm: 28
    18:
      enable: true
      csm: 17
    19:
      enable: true
      csm: 18
    20:
      enable: true
      csm: 19
    21:
      enable: true
      csm: 30
    22:
      enable: true
      csm: 29
    23:
      enable: true
      csm: 16