price:
  enable: true
  min: 1000.0
  max: 100000.0

gameconfig:
  spdrawchance: 20.0
  coin: 10
  bet: 2
  round: 3
  clocktime: 30



cardconfig:
  spcardmaterial: PAPER
  cardmaterial: PAPER
  invisiblecsm: 0

  cardcsm:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11

  spcards:
    1:
      enable: true
      csm: 0