name: BlackJackPlus
version: 1.0
main: tororo1066.blackjackplus.BlackJackPlus
api-version: 1.17

softdepend:
  - Man10CommonLibs
depend:
  - Vault
  - ProtocolLib


commands:
  blackjackplus:
    aliases:
      - bjp